### PR TITLE
Fix issue #512: clang analyzer 14 warning about a possible NULL deref.

### LINKED ISSUE #512: Fix a clang analyzer 14 warning about a possible NULL deref.
https://github.com/sudo-project/sudo/commit/bfc6249902d842626058e74074832930feaf2f80

### PR DESCRIPTION
**Pull request by edmonds**
Import https://github.com/sudo-project/sudo/commit/bfc6249902d842626058e74074832930feaf2f80 to fix #512.

### CODE REVIEW

File: protobuf-c/protobuf-c.c [hunk 1]
```diff
@@ -3231,6 +3231,9 @@ protobuf_c_message_unpack(const ProtobufCMessageDescriptor *desc,
 	/* allocate space for repeated fields, also check that all required fields have been set */
 	for (f = 0; f < desc->n_fields; f++) {
 		const ProtobufCFieldDescriptor *field = desc->fields + f;
+		if (field == NULL) {
```
Comment (MatkovIvan) [inline protobuf-c/protobuf-c.c:3234]: @edmonds I guess checking `desc->fields` before the loop would be the more correct fix
